import type { Metadata } from "next";
import { Inter } from "next/font/google";

import localFont from 'next/font/local'

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { BatchSystemTaskContextProvider } from "./context/BatchSystemTaskContextProvider";
import ThemeSwitcher from "./components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BatchSystemTask",
  description: "Generated by create next app",
};


// const myFont = localFont({
//   src: './fonts/ClashDisplay_Complete/Fonts/WEB/fonts/ClashDisplay-Regular.woff2',
// })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`border-blue-700 pinkBorderClass  borderClass w-full max-w-[1440px] flex mx-auto justify-end items-center relative bg-background
      `} >

        <BatchSystemTaskContextProvider>
          <ThemeSwitcher>
            <div className={`border-yellow-800 pinkBorderClass max-w-[1440px] w-full  flex flex-col items-end  
            `} >

              <Header />
              {children}
              <Footer />
            </div>

          </ThemeSwitcher>
        </BatchSystemTaskContextProvider>

        <div className={`backBackground backSoftLightImg  border-8 border-blue-900 absolute w-full h-full mix-blend-soft-light bg-blend-soft-light`}>
        </div>

      </body>
    </html >
  );
}
