import type { Metadata } from "next";
import { Inter } from "next/font/google";

import localFont from 'next/font/local'

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { BatchSystemTaskContextProvider } from "./context/BatchSystemTaskContextProvider";
import ThemeSwitcher from "./components/ThemeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BatchSystemTask",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={` pinkBorderClass borderClass w-full max-w-[1440px] flex mx-auto justify-end items-center relative bg-background 
      `} >

        <BatchSystemTaskContextProvider>
          <ThemeSwitcher>
            <div className={`borderClass max-w-[1440px] w-full  flex flex-col items-end  
            `} >

              <Header />
              {children}
              <Footer />
            </div>

          </ThemeSwitcher>
        </BatchSystemTaskContextProvider>

        <div className={`borderClass backBackground backSoftLightImg absolute w-full h-full mix-blend-soft-light bg-blend-soft-light`}>
        </div>

      </body>
    </html >
  );
}
